general {
    lock_cmd = pidof hyprlock || hyprlock       # Избегаем запуска нескольких копий / Avoid starting multiple copies
    before_sleep_cmd = loginctl lock-session    # Блокировка перед сном / Lock before sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Включаем экран после сна / Turn on screen after sleep
}

listener {
    timeout = 150                                # 2.5 мин / 2.5 mins
    on-timeout = brightnessctl -s set 10         # Уменьшаем яркость экрана / Decrease screen brightness
    on-resume = brightnessctl -r                 # Возвращаем яркость / Restore brightness
}

listener {
    timeout = 300                                 # 5 мин / 5 mins
    on-timeout = loginctl lock-session            # Блокируем экран / Lock screen
}

listener {
    timeout = 330                                 # 5.5 мин / 5.5 mins
    on-timeout = hyprctl dispatch dpms off        # Отключаем дисплей / Turn off display
    on-resume = hyprctl dispatch dpms on          # Включаем дисплей при активности / Turn on display on activity
}

listener {
    timeout = 1800                                # 30 мин / 30 mins
    on-timeout = systemctl suspend                # Спящий режим / Suspend system
}
